INSERT OR IGNORE INTO cards (card_name, rarity, type, elixir_cost, is_hero, is_evolved)
VALUES

-- Tower Cards --
('Tower Princess', 'Common', 'Tower', 0, 0, 0),
('Cannoneer', 'Epic', 'Tower', 0, 0, 0),
('Dagger Duchess', 'Legendary', 'Tower', 0, 0, 0),
('Royal Chef', 'Legendary', 'Tower', 0, 0, 0),

-- Champion Cards -- 
('Mighty Miner', 'Champion', 'Champion', 4, 0, 0),
('Archer Queen', 'Champion', 'Champion', 5, 0, 0),
('Goblinstein', 'Champion', 'Champion', 5, 0, 0),
('Skeleton King', 'Champion', 'Champion', 4, 0, 0),
('Golden Knight', 'Champion', 'Champion', 4, 0, 0),
('Boss Bandit', 'Champion', 'Champion', 6, 0, 0),
('Little Prince', 'Champion', 'Champion', 3, 0, 0),

-- Common Card --
('Berserker', 'Common', 'Normal', 2, 0, 0),
('Fire Spirit', 'Common', 'Normal', 1, 0, 0),
('Electro Spirit', 'Common', 'Normal', 1, 0, 0),
('Bats', 'Common', 'Normal', 2, 0, 1),
('Bomber', 'Common', 'Normal', 2, 0, 1),
('Arrows', 'Common', 'Normal', 3, 0, 0),
('Royal Delivery', 'Common', 'Normal', 3, 0, 0),
('Skeleton Barrel', 'Common', 'Normal', 3, 0, 1),
('Minions', 'Common', 'Normal', 3, 0, 0),
('Skeleton Dragons', 'Common', 'Normal', 4, 0, 0),
('Mortar', 'Common', 'Normal', 4, 0, 1),
('Minion Horde', 'Common', 'Normal', 5, 0, 0),
('Barbarians', 'Common', 'Normal', 5, 0, 1),
('Rascals', 'Common', 'Normal', 5, 0, 0),
('Elite Barbarians', 'Common', 'Normal', 6, 0, 0),
('Royal Recruits', 'Common', 'Normal', 7, 0, 1),
('Ice Spirit', 'Common', 'Normal', 1, 0, 1),
('Giant Snowball', 'Common', 'Normal', 2, 0, 1),
('Goblins', 'Common', 'Normal', 2, 0, 0),
('Goblin Gang', 'Common', 'Normal', 3, 0, 0),
('Royal Giant', 'Common', 'Normal', 6, 0, 1),
('Skeletons', 'Common', 'Normal', 1, 0, 1),
('Cannon', 'Common', 'Normal', 3, 0, 1),
('Spear Goblins', 'Common', 'Normal', 2, 0, 0),
('Zap', 'Common', 'Normal', 2, 0, 1),
('Firecracker', 'Common', 'Normal', 3, 0, 1),
('Knight', 'Common', 'Normal', 3, 1, 1),
('Archers', 'Common', 'Normal', 3, 0, 1),
('Tesla', 'Common', 'Normal', 4, 0, 1),

-- Rare cards --
('Suspicious Bush', 'Rare', 'Normal', 2, 0, 0),
('Heal Spirit', 'Rare', 'Normal', 1, 0, 0),
('Dart Goblin', 'Rare', 'Normal', 3, 0, 1),
('Goblin Demolisher', 'Rare', 'Normal', 4, 0, 0),
('Goblin Hut', 'Rare', 'Normal', 4, 0, 0),
('Battle Ram', 'Rare', 'Normal', 4, 0, 1),
('Bomb Tower', 'Rare', 'Normal', 4, 0, 0),
('Furnace', 'Rare', 'Normal', 4, 0, 1),
('Royal Hogs', 'Rare', 'Normal', 5, 0, 1),
('Wizard', 'Rare', 'Normal', 5, 0, 1),
('Rocket', 'Rare', 'Normal', 6, 0, 0),
('Ice Golem', 'Rare', 'Normal', 2, 0, 0),
('Mega Minion', 'Rare', 'Normal', 3, 0, 0),
('Elixir Golem', 'Rare', 'Normal', 3, 0, 0),
('Tombstone', 'Rare', 'Normal', 3, 0, 0),
('Mini P.E.K.K.A', 'Rare', 'Normal', 4, 1, 0),
('Valkyrie', 'Rare', 'Normal', 4, 0, 1),
('Battle Healer', 'Rare', 'Normal', 4, 0, 0),
('Zappies', 'Rare', 'Normal', 4, 0, 0),
('Goblin Cage', 'Rare', 'Normal', 4, 0, 1),
('Flying Machine', 'Rare', 'Normal', 4, 0, 0),
('Giant', 'Rare', 'Normal', 5, 1, 0),
('Elixir Collector', 'Rare', 'Normal', 6, 0, 0),
('Barbarian Hut', 'Rare', 'Normal', 6, 0, 0),
('Three Musketeers', 'Rare', 'Normal', 9, 0, 0),
('Inferno Tower', 'Rare', 'Normal', 5, 0, 0),
('Earthquake', 'Rare', 'Normal', 3, 0, 0),
('Fireball', 'Rare', 'Normal', 4, 0, 0),
('Musketeer', 'Rare', 'Normal', 4, 1, 1),
('Hog Rider', 'Rare', 'Normal', 4, 0, 0),

-- Epic cards --
('Vines', 'Epic', 'Normal', 3, 0, 0),
('Goblin Curse', 'Epic', 'Normal', 2, 0, 0),
('Wall Breakers', 'Epic', 'Normal', 2, 0, 1),
('Clone', 'Epic', 'Normal', 3, 0, 0),
('Goblin Drill', 'Epic', 'Normal', 4, 0, 1),
('Freeze', 'Epic', 'Normal', 4, 0, 0),
('Baby Dragon', 'Epic', 'Normal', 4, 0, 1),
('Electro Dragon', 'Epic', 'Normal', 5, 0, 1),
('Cannon Cart', 'Epic', 'Normal', 5, 0, 0),
('Executioner', 'Epic', 'Normal', 5, 0, 1), 
('Prince', 'Epic', 'Normal', 5, 0, 0),
('Bowler', 'Epic', 'Normal', 5, 0, 0),
('X-Bow', 'Epic', 'Normal', 6, 0, 0), 
('Goblin Giant', 'Epic', 'Normal', 6, 0, 1),
('Giant Skeleton', 'Epic', 'Normal', 6, 0, 0),
('Electro Giant', 'Epic', 'Normal', 7, 0, 0),
('Mirror', 'Epic', 'Normal', 1, 0, 0), 
('Rage', 'Epic', 'Normal', 2, 0, 0), 
('Barbarian Barrel', 'Epic', 'Normal', 2, 0, 0),
('Void', 'Epic', 'Normal', 3, 0, 0),
('Goblin Barrel', 'Epic', 'Normal', 3, 0, 1),
('Guards', 'Epic', 'Normal', 3, 0, 0), 
('Tornado', 'Epic', 'Normal', 3, 0, 0), 
('Rune Giant', 'Epic', 'Normal', 4, 0, 0),
('Poison', 'Epic', 'Normal', 4, 0, 0),
('Hunter', 'Epic', 'Normal', 4, 0, 1),
('Witch', 'Epic', 'Normal', 5, 0, 1), 
('Lightning', 'Epic', 'Normal', 6, 0, 0),
('P.E.K.K.A ', 'Epic', 'Normal', 7, 0, 1),
('Golem', 'Epic', 'Normal', 8, 0, 0),
('Skeleton Army', 'Epic', 'Normal', 3, 0, 1),
('Dark Prince', 'Epic', 'Normal', 4, 0, 0),
('Balloon', 'Epic', 'Normal', 5, 0, 0),

-- Legendary cards --
('Electro Wizard','Legendary', 'Normal', 4, 0, 0),
('Goblin Machine', 'Legendary', 'Normal', 5, 0, 0),
('Spirit Empress', 'Legendary', 'Normal', 6, 0, 0),
('Lava Hound', 'Legendary', 'Normal', 7, 0, 0),
('Miner', 'Legendary', 'Normal', 3, 0, 0),
('Fisherman', 'Legendary', 'Normal', 3, 0, 0),
('Ice Wizard', 'Legendary', 'Normal', 3, 0, 0),
('Royal Ghost', 'Legendary', 'Normal', 3, 0, 1),
('Princess', 'Legendary', 'Normal', 3, 0, 0),
('Phoenix', 'Legendary', 'Normal', 4, 0, 0), 
('Magic Archer', 'Legendary', 'Normal', 4, 0, 0),
('Night Witch', 'Legendary', 'Normal', 4, 0, 0),
('Lumberjack', 'Legendary', 'Normal', 4, 0, 1),
('Inferno Dragon', 'Legendary', 'Normal', 4, 0, 1), 
('Graveyard', 'Legendary', 'Normal', 5, 0, 0),
('Ram Rider', 'Legendary', 'Normal', 5, 0, 0),
('Sparky', 'Legendary', 'Normal', 6, 0, 0),
('Mega Knight', 'Legendary', 'Normal', 7, 0, 1),
('Mother Witch', 'Legendary', 'Normal', 4, 0, 0),
('Bandit', 'Legendary', 'Normal', 3, 0, 0),
('The Log', 'Legendary', 'Normal', 2, 0, 0)